providers = ["python", "node"]

[phases.setup]
nixPkgs = ["python311", "nodejs-18_x"]

[phases.install]
cmds = [
    "cd frontend && npm install",
    "pip install -r backend/requirements.txt"
]

[phases.build]
cmds = [
    "cd frontend && npm run build"
]

[start]
cmd = "python backend/manage.py migrate && python backend/manage.py collectstatic --noinput && gunicorn --pythonpath backend fsm_core.wsgi:application"