services:
  - type: web
    name: aj-long-electric-backend
    runtime: python3
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/manage.py migrate && python backend/manage.py collectstatic --noinput && gunicorn --pythonpath backend fsm_core.wsgi:application
    plan: free
    healthCheckPath: /api/health/
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: DJANGO_SETTINGS_MODULE
        value: fsm_core.settings.production
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "aj-long-electric-backend.onrender.com,aj-long-electric.onrender.com,localhost,127.0.0.1"
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: aj-long-electric-db
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        value: "https://aj-long-electric.onrender.com,https://aj-long-electric.com,https://www.aj-long-electric.com"

databases:
  - name: aj-long-electric-db
    databaseName: fsm_database
    user: fsm_user
    plan: free