# Prometheus configuration for AJ Long Electric FSM monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:8080']
    metrics_path: '/nginx_status'
    scrape_interval: 10s

  # Django backend metrics
  - job_name: 'django-backend'
    static_configs:
      - targets: 
        - 'backend1:8000'
        - 'backend2:8000'
        - 'backend3:8000'
    metrics_path: '/metrics'
    scrape_interval: 10s

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s

  # Frontend application metrics
  - job_name: 'frontend'
    static_configs:
      - targets:
        - 'frontend1:3000'
        - 'frontend2:3000'
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Custom application metrics
  - job_name: 'fsm-api'
    static_configs:
      - targets: ['nginx:443']
    metrics_path: '/api/metrics'
    scheme: https
    scrape_interval: 30s
    tls_config:
      insecure_skip_verify: true

# Recording rules for aggregations
rule_files:
  - "/etc/prometheus/rules/fsm_rules.yml"